### ISSUE TITLE
Formatting is broken for `<` character

### ISSUE THREAD

**Issue by Xstoudi** [Julien-R44/adonis-vscode-extension#20]
## Package version
0.9.1

## Node.js and npm version
N/A

## Sample Code (to reproduce the issue)
When formatting this code:
```
@if(paintings.lastPage > paintings.currentPage)
<li>
  Whatever
</li>
@end
```
is correctly formatted (remains the same), while the following one just get mad:
```
@if(paintings.lastPage < paintings.currentPage)
<li>
  Whatever
</li>
@end
```

and end up formatted like this:
```
@if(paintings.lastPage < paintings.currentPage) <li>
  Whatever
  </li>
  @end
```

I think it related to the `<` character.

**Comment by 25Das** [comment]
Really no attention to this? I can't use the formatter at all because it breaks HTML. Any workaround?

**Comment by Julien-R44** [comment]
Actually, the actual formatter is not really a formatter. It's just a super basic thing that I did quickly so there are a lot of unhandled cases.

Making a formatter for Edge is a pretty complicated task to do. To get an idea have a look at this repo for Blade 
https://github.com/shufo/blade-formatter
https://github.com/shufo/vscode-blade-formatter
https://github.com/shufo/prettier-plugin-blade

We need almost the same thing, knowing that Blade and Edge share almost the same syntax.
I was planning to fork it and make the necessary modifications but I didn't find the time nor the motivation.

@25Das So feel free to take care of it. :) 

I'm closing the issue in the meantime because it's not really related to this repo. 
If a formatter is developped, then, in my mind, it will be a CLI tool that will then be used by this VSCode extension, and/or by a prettier plugin.
